-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 12:36:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi` DEFAULT CHARACTER SET latin1 ;
USE `pi` ;

-- -----------------------------------------------------
-- Table `pi`.`precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`precio` (
  `sucursal_id` VARCHAR(50) NOT NULL,
  `producto_id` VARCHAR(255) NOT NULL,
  `precio` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pi`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`producto` (
  `producto_id` VARCHAR(255) NOT NULL,
  `marca` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `presentacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`producto_id`),
  CONSTRAINT `producto_id`
    FOREIGN KEY ()
    REFERENCES `pi`.`precio` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pi`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`sucursal` (
  `sucursal_id` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `comercioId` BIGINT(20) NULL DEFAULT NULL,
  `banderaId` BIGINT(20) NULL DEFAULT NULL,
  `banderaDescripcion` VARCHAR(255) NULL DEFAULT NULL,
  `comercioRazonSocial` VARCHAR(255) NULL DEFAULT NULL,
  `provincia` VARCHAR(255) NULL DEFAULT NULL,
  `localidad` VARCHAR(255) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `lat` DOUBLE NULL DEFAULT NULL,
  `lng` DOUBLE NULL DEFAULT NULL,
  `sucursalNombre` VARCHAR(255) NULL DEFAULT NULL,
  `sucursalTipo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`sucursal_id`),
  CONSTRAINT `sucursal_id`
    FOREIGN KEY ()
    REFERENCES `pi`.`precio` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
